application: onlinecrossie
version: 2
runtime: python
api_version: 1

default_expiration: "7d"

handlers:
- url: /api/v1/.*
  script: crossie_app.py
  login: required

- url: /
  static_files: index.html
  upload: index.html
  login: required

- url: /favicon.ico
  static_files: static_files/favicon.ico
  upload: static_files/favicon.ico

- url: /static_files
  static_dir: static_files
  login: required

- url: /admin/v1/.*
  script: admin_ops.py
  login: admin

- url: /public/v1/.*
  script: public.py
